[mysql]
  dbname     = "sqlboiler_hands_on"
  host       = "172.17.0.1"
  port       = 3306
  user       = "root"
  pass       = "password"
  sslmode    = "false"
  whitelist = [
    "articles",
    "users"
  ]