[mysql]
  dbname     = "sqlboiler_demo"
  host       = "localhost"
  port       = 3308
  user       = "root"
  pass       = "password"
  sslmode    = "false"
  whitelist = [
    "articles",
    "users"
  ]